# This workflow will install Python dependencies,
# run the python script to generate the database,
# and upload the regenerated database to the binary repo

name: Generate Database

on:
  # More details on trigger events: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:  # manual execution
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:

    # Specify the environment to use (access to env variables)
    env: gh-actions

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/dr-rodriguez/AstrodbKit2

    - name: Generate sqlite (file) database
      run: |
        python scripts/tutorials/generate_database.py sqlite
      working-directory: .

    - name: Generate postgres (Heroku) database
      run: |
          python scripts/tutorials/generate_database.py postgres
        working-directory: .

    - name: Push database file
      uses: dmnemec/copy_file_to_another_repo_action@main
      # Details for this action at https://github.com/marketplace/actions/push-a-file-to-another-repository
      env:
          API_TOKEN_GITHUB: ${{ env.SIMPLE_TOKEN }}
      with:
          source_file: 'SIMPLE.db'
          destination_repo: 'SIMPLE-AstroDB/SIMPLE-binary'
          destination_branch: 'main'
          user_email: 'github-actions@github.com'
          user_name: 'github-actions'
